import { chatApi } from '@/store/api/chat/core';

export { chatApi };
export { patchConversationsFromNewMessage } from '@/store/api/chat/cache';

export type {
  CreateConversationRequest,
  SendMessageRequest,
  EditMessageRequest,
  DeleteMessageRequest,
  RecallMessageRequest,
  MarkAsReadRequest,
  PinMessageRequest,
  ReactMessageRequest,
  UpdateGroupRequest,
  AddMembersRequest,
  ChangeMemberRoleRequest,
  CreatePollRequest,
  CreateTaskRequest,
  UpdateTaskStatusRequest,
} from '@/store/api/chat/types';

export const {
  useGetConversationsQuery,
  useGetMessagesQuery,
  useGetConversationMembersQuery,
  useCreateConversationMutation,
  useSendMessageMutation,
  useEditMessageMutation,
  useDeleteMessageMutation,
  useRecallMessageMutation,
  useMarkAsReadMutation,
  usePinMessageMutation,
  useUnpinMessageMutation,
  useReactMessageMutation,
  useUpdateGroupMutation,
  useDeleteGroupMutation,
  useLeaveGroupMutation,
  useAddMembersMutation,
  useRemoveMemberMutation,
  useChangeMemberRoleMutation,
  useJoinRequestMutation,
  useApproveRequestMutation,
  useRejectRequestMutation,
  useCreatePollMutation,
  useVotePollMutation,
  useUnvotePollMutation,
  useCreateTaskMutation,
  useUpdateTaskStatusMutation,
  useGenerateAIRecapMutation,
  useGetPollsQuery,
  useGetTasksQuery,
  useGetGroupRequestsQuery,
  useGetLatestAIRecapQuery,
} = chatApi;
